INSERT INTO departements( nom_dept ) VALUES ( 'Informatique');
INSERT INTO departements( nom_dept ) VALUES ( 'Management');
INSERT INTO departements( nom_dept ) VALUES ( 'RH');
INSERT INTO services( nom_service, etat_service, id_dept_service ) VALUES ( 'Ressources Humaines', 1, 1);
INSERT INTO services( nom_service, etat_service, id_dept_service ) VALUES ( 'Développement Web', 1, 1);
INSERT INTO services( nom_service, etat_service, id_dept_service ) VALUES ( 'Marketing', 1, 1);
INSERT INTO services( nom_service, etat_service, id_dept_service ) VALUES ( 'Finance', 1, 1);
INSERT INTO services( nom_service, etat_service, id_dept_service ) VALUES ( 'Support Technique', 1, 1);
INSERT INTO users( nom_user, email_user, mdp_user, est_admin, etat_user ) VALUES ( 'User 1', 'user1@admin.com', '1234', 1, 1);
INSERT INTO users( nom_user, email_user, mdp_user, est_admin, etat_user ) VALUES ( 'User 2', 'user2@admin.com', '1234', 1, 1);
INSERT INTO users( nom_user, email_user, mdp_user, est_admin, etat_user ) VALUES ( 'User 3', 'user3@admin.com', '1234', 1, 1);
INSERT INTO information_users( id_user_information_user, nom_info, prenom_info, sexe_info, date_naissance_info, contact_info, addresse_info, etat_info ) VALUES ( 1, 'Doe', 'John', 'M', '1985-05-20', 'john.doe@email.com', '123 Main Street', 1);
INSERT INTO information_users( id_user_information_user, nom_info, prenom_info, sexe_info, date_naissance_info, contact_info, addresse_info, etat_info ) VALUES ( 2, 'Smith', 'Alice', 'F', '1990-08-15', 'alice.smith@email.com', '456 Elm Street', 1);
INSERT INTO information_users( id_user_information_user, nom_info, prenom_info, sexe_info, date_naissance_info, contact_info, addresse_info, etat_info ) VALUES ( 3, 'Johnson', 'Bob', 'M', '1988-03-10', 'bob.johnson@email.com', '789 Oak Avenue', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 3, '2023-09-29 02.33.58 PM', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 3, '2023-09-29 02.35.51 PM', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 3, '2023-09-29 02.36.02 PM', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 5, '2023-09-29 02.37.15 PM', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 5, '2023-09-29 02.37.22 PM', 1);
INSERT INTO recrutements( id_service_recrutement, dateheure_recrutement, etat_recrutement ) VALUES ( 3, '2023-10-01 06.18.37 PM', 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-05 04.59.00 PM', 2, 'aragerg', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-05 07.15.00 PM', 2, 'andoharanofotsy', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-05 07.15.00 PM', 2, 'andoharanofotsy', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-27 09.21.00 PM', 2, 'mahazina', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-12 08.23.00 PM', 2, 'analakely', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-08 01.13.00 AM', 1, 'Ivato', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-08 01.13.00 AM', 1, 'Ivato', 13, 1);
INSERT INTO tests( dateheure_test, id_user_test, lieu_test, id_recrutement_test, etat_test ) VALUES ( '2023-10-08 01.13.00 AM', 1, 'Ivato', 13, 1);
INSERT INTO user_departements( id_user_user_dept, id_dept_user_dept ) VALUES ( 1, 1);
INSERT INTO user_departements( id_user_user_dept, id_dept_user_dept ) VALUES ( 2, 1);
INSERT INTO user_departements( id_user_user_dept, id_dept_user_dept ) VALUES ( 3, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 7, 50, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 8, 50, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 9, 50, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 10, 2, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 11, 2, 1);
INSERT INTO besoins( id_recrutement_besoin, homme_jour, etat_besoin ) VALUES ( 13, 50, 1);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 7, 'diplome', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 7, 'sexe', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 8, 'diplome', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 8, 'sexe', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 9, 'diplome', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 9, 'sexe', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 10, 'Nationalite', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 10, 'experience', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 11, 'Nationalite', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 11, 'experience', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 13, 'diplome', 1, null);
INSERT INTO criteres( id_recrutement_critere, descri_critere, etat_critere, fichier_critere ) VALUES ( 13, 'sexe', 1, null);
INSERT INTO cv( id_info_user_cv, dateheure_remplissage, id_recrutement_cv, etat_cv ) VALUES ( 4, '2023-10-03 02.03.11 PM', 13, 1);
INSERT INTO cv( id_info_user_cv, dateheure_remplissage, id_recrutement_cv, etat_cv ) VALUES ( 5, '2023-10-03 02.03.11 PM', 13, 1);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 11, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 10, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 11, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 10, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 11, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 2, 10, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 1, 11, 13);
INSERT INTO cv_selections( id_user_cv_selection, id_cv_selected, id_recrutement_cv_selection ) VALUES ( 1, 10, 13);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 1, 'age ?', 5, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 1, 'mafy ve za ?', 50, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 5, 'age ?', 10, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 5, 'mafy ve za ?', 20, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 6, 'TIM', 10, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 6, 'mafy ve za ?', 100, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 7, 'TIM', 10, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 7, 'mafy ve za ?', 100, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 8, 'TIM', 10, 1);
INSERT INTO questionnaires( id_test_questionnaire, question, coefficient_question, etat_questionnaire ) VALUES ( 8, 'mafy ve za ?', 100, 1);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'bacc', 2, 12);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'master', 10, 12);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'male', 1, 13);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'femelle', 0, 13);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'bacc', 2, 14);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'master', 10, 14);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'male', 1, 15);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'femelle', 0, 15);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'bacc', 2, 16);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'master', 10, 16);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'male', 1, 17);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'femelle', 0, 17);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'malgache', 5, 18);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'etranger', 1, 18);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '0 - 2 ans', 2, 19);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '3 - 5 ans', 10, 19);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '6 - 10 ans', 11, 19);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'malgache', 5, 20);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'etranger', 1, 20);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '0 - 2 ans', 2, 21);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '3 - 5 ans', 10, 21);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( '6 - 10 ans', 11, 21);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'bacc', 2, 22);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'master', 10, 22);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'male', 1, 23);
INSERT INTO choix_criteres( choix_critere, coefficient_critere, id_critere_choix ) VALUES ( 'femelle', 0, 23);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 10, 12, 18);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 10, 13, 19);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 10, 14, 20);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 10, 15, 21);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 10, 16, 22);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 11, 12, 41);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 11, 13, 35);
INSERT INTO cv_reponses( id_cv_cv_reponse, id_critere_cv_reponse, id_choix_cv_reponse ) VALUES ( 11, 14, 26);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 1, '5', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 1, '10', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 1, '20', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 1, '30', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 1, '40', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 2, 'non', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 2, 'oui', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 6, '5', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 6, '10', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 6, '20', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 7, 'non', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 7, 'oui', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 7, 'peut etre', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 8, 'T', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 8, 'I', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 8, 'M', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 9, 'YES', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 9, 'NO', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 9, 'MAYBE', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 10, 'T', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 10, 'I', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 10, 'M', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 11, 'YES', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 11, 'NO', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 11, 'MAYBE', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 12, 'T', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 12, 'I', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 12, 'M', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 13, 'YES', 1);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 13, 'NO', 0);
INSERT INTO questionnaire_reponses( id_questionnaire_questionnaire_reponse, questionnaire_reponse, est_vrai ) VALUES ( 13, 'MAYBE', 0);